site_name: OS-Car-Man
theme:
  name: material
        # highlightjs: true
        # hljs_languages:
        #     - python
  language: ru
  palette:
    primary: black
  features:
    - content.code.copy
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye

repo_name: westandskif/os-car-man
repo_url: https://github.com/westandskif/os-car-man
edit_uri: edit/main/docs/

nav:
  - "Zeekr из Китая - Общее":
     - Введение: README.md
     - "WeChat & eSender": wechat_n_esender.md
     - "Активация машины / RNR": activate_car.md
     - "Голосовые команды на китайском": voice_commands.md
     - "Мобильное приложение": mobile_app.md
  - "Zeekr из Китая - FAQ": FAQ.md
  - "Zeekr из Китая - Обслуживание": service.md
  - "Zeekr из Китая - Документы": documents.md
  - "Поучаствовать": CONTRIBUTING.md
  - "О проекте": about.md

markdown_extensions:
  - toc:
      slugify: !!python/name:markdown.extensions.toc.slugify
      permalink: true
  - admonition
  - pymdownx.details
  - tables
  - footnotes
  - markdown_include.include:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search

hooks:
  - hooks/patch_slugify.py
